---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Install the nodejs
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: present

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory ~/web/
  file:
    path: ~/web
    state: directory

- name: copy file
  copy:
    src: files/index.js
    dest: ~/web/index.js

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f